# Generated by Django 4.0.2 on 2022-02-14 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_id', models.CharField(max_length=255)),
                ('external_id', models.UUIDField()),
                ('iban', models.CharField(max_length=32)),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_id', models.CharField(max_length=255)),
                ('external_id', models.CharField(max_length=255)),
                ('booking_date', models.DateField()),
                ('creditor_account', models.CharField(max_length=32, null=True)),
                ('creditor_name', models.CharField(max_length=255, null=True)),
                ('debtor_account', models.CharField(max_length=32, null=True)),
                ('debtor_name', models.CharField(max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('iban', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nordigen_client_app.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_id', models.CharField(max_length=255)),
                ('institution_id', models.CharField(max_length=255)),
                ('reference_id', models.CharField(max_length=255)),
                ('is_granted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Institution accesses',
            },
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_booked', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('expected', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('forward_available', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('interim_available', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('interim_booked', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('non_invoiced', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('opening_booked', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nordigen_client_app.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'account_id'], name='nordigen_cl_user_id_777fad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('user', 'account_id', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='institutionaccess',
            index=models.Index(fields=['user', 'institution_id', 'reference_id'], name='nordigen_cl_user_id_b8dcf3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='institutionaccess',
            unique_together={('agreement_id', 'institution_id')},
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'institution_id', 'iban'], name='nordigen_cl_user_id_3002b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('user', 'iban')},
        ),
    ]
